# Generated by Django 5.2.6 on 2025-09-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VOTE', 'Vote Cast'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=20),
        ),
    ]
